name: main_widgets
description: "A Flutter package for efficient UI state management, handling loading, empty views, content display, caching, and pull-to-refresh with customizable widgets."
version: 0.2.4
homepage: https://github.com/abdelrahmanghanem
repository: https://github.com/abdelrahmanghanem/main_widgets


environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.0
  intl: ^0.19.0
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  smart_localize: ^0.0.13
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
